apiVersion: v1
kind: Namespace
metadata:
  name: loadwatcher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-watcher-deployment
  namespace: loadwatcher
  labels:
    app: load-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-watcher
  template:
    metadata:
      labels:
        app: load-watcher
    spec:
      containers:
      - name: load-watcher
        image: registry.gitlab.bsc.es/datacentric-computing/cloudskin-project/cloudskin-registry/load-watcher:latest
        imagePullPolicy: Always
        env:
        - name: METRICS_PROVIDER_NAME
          value: Prometheus
        - name: METRICS_PROVIDER_ADDRESS
          value: http://prometheus-k8s.monitoring.svc:9090
#        - name: WATCH_HOST
#          value: cloudskin-k8s-edge-worker-0.novalocal 
        - name: WATCH_POD_REGEX
          value: torchserve-.*
        - name: WATCH_GREENANALYSE
          value: "true"
        - name: WATCH_INCLUDE_TS
          value: "true"
        - name: WATCH_INCLUDE_USERS
          value: "true"
        ports:
        - containerPort: 2020
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - torchserve
            topologyKey: kubernetes.io/hostname
            namespaces:
            - torchservetest
---
apiVersion: v1
kind: Service
metadata:
  namespace: loadwatcher
  name: load-watcher
  labels:
    app: load-watcher
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 2020
    targetPort: 2020
    protocol: TCP
  selector:
    app: load-watcher
